name: sklearn-env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - scikit-learn=1.3.2
  - scipy
  - imbalanced-learn
  - numpy=1.24.3
  - xgboost
  - pandas
  - seaborn
  - matplotlib
  - pip:  
    - azureml-mlflow
    - mlflow==2.17.2
    - azure-ai-ml
    - azureml-inference-server-http
